Repository Team-Code-Wizards/frontend, pull requests merged in 2024-01, with the labels that each got.

#42 Feature/interaction
  README.md
  src/app/globals.scss
  src/components/Interaction/Step/index.tsx
  src/components/Interaction/Step/interface.ts
  src/components/Interaction/Step/style.module.scss
  src/components/Interaction/index.tsx
  src/components/Interaction/interface.ts
  src/components/Interaction/styles.module.scss
  src/components/MainPage/index.tsx
  src/constants/Interaction/index.ts
  src/constants/Interaction/type.ts
  src/constants/index.ts
  src/images/interaction/1-attention.png
  src/images/interaction/2-communication.png
  src/images/interaction/3-design.png
  src/images/interaction/4-approach.png
  src/images/interaction/5-testing.png
  src/images/interaction/6-support.png
  src/images/interaction/background.png
Labels: enhancement

#53 Feature/privacy-policy
  .github/workflows/main.yml
  .gitignore
  next.config.js
  src/app/privacy-policy/page.tsx
  src/app/privacy-policy/style.module.scss
  src/components/notFound/styles.module.scss
  tsconfig.json
Labels: Готово

#57 Feature/services-section
  src/components/MainPage/index.tsx
  src/components/Services/index.tsx
  src/components/Services/style.module.scss
  src/constants/Services/index.ts
  src/constants/index.ts
Labels: Готово (есть 2 апрува)

#64 Feature/footer
  src/components/Contacts/index.tsx
  src/components/Footer/index.tsx
  src/components/Footer/styles.module.scss
  src/components/MainPage/index.tsx
  src/images/logo/logo-no-text.svg
  src/images/logo/logo-text.svg
Labels: Готово (есть 2 апрува), Апрув + Мелкие правки

#40 Feature/guarantee-component
  .eslintignore
  README.md
  infra/next.config.js
  package-lock.json
  package.json
  src/app/globals.scss
  src/app/normalize.css
  src/components/Guarantee/index.tsx
  src/components/Guarantee/interface.ts
  src/components/Guarantee/styles.module.scss
  src/components/GuaranteeCard/index.tsx
  src/components/GuaranteeCard/interface.ts
  src/components/GuaranteeCard/styles.module.scss
  src/components/MainPage/index.tsx
  src/constants/Guarantee/index.ts
  src/constants/Guarantee/type.ts
  src/constants/index.ts
  src/images/guarantee/background.jpg
  src/images/guarantee/background.png
  src/images/guarantee/coherent.svg
  src/images/guarantee/contract.svg
  src/images/guarantee/deadline.svg
  src/images/guarantee/quality.svg
  src/images/guarantee/security.svg
  src/images/guarantee/support.svg
  src/images/guarantee/unique.svg
Labels: Готово (есть 2 апрува)

#54 Feature/modal-component
  src/app/globals.scss
  src/components/MainPage/index.tsx
  src/components/Modal/ModalItem/index.tsx
  src/components/Modal/ModalItem/interface.ts
  src/components/Modal/ModalItem/style.module.scss
  src/components/Modal/index.tsx
  src/components/Modal/style.module.scss
  src/components/Сhoice/ChoiceCard/index.tsx
  src/components/Сhoice/ChoiceCard/interface.ts
  src/components/Сhoice/ChoiceCard/style.module.scss
  src/components/Сhoice/index.tsx
  src/constants/ModalWindow/index.ts
  src/constants/ModalWindow/type.ts
  src/constants/index.ts
  src/images/choice/arrow-1.svg
  src/images/choice/arrow-2.svg
  src/images/choice/attraction-bg.png
  src/images/choice/design-bg.png
  src/images/choice/index.tsx
  src/images/choice/optimization-bg.png
  src/images/choice/percent-bg.png
  src/images/choice/planet-bg.png
  src/images/choice/presence-bg.png
  src/images/choice/safety-bg.png
  src/images/modal/IconArrow.tsx
  src/images/modal/IconClose.tsx
Labels: Исправлено (проверьте)

#69 Feature/header-top
  src/components/AboutUs/style.module.scss
  src/components/Header/index.tsx
  src/components/Header/style.module.scss
  src/components/MainPage/index.tsx
  src/images/header/logo-header.svg
Labels: Исправлено (проверьте)

#52 Feature/create-stages
  src/app/globals.scss
  src/components/MainPage/index.tsx
  src/components/StageCreate/index.tsx
  src/components/StageCreate/style.module.scss
  src/components/Сhoice/index.tsx
  src/images/stage/background.png
  src/images/stage/index.tsx
Labels: Готово (есть 2 апрува)

#73 Feature/site-description-modal
  src/components/MainPage/index.tsx
  src/components/ProjectDescriptionModal/index.tsx
  src/components/ProjectDescriptionModal/style.module.scss
  src/components/TechStack/style.module.scss
  src/images/modal/projectDescription/landing-image.png
  src/images/techStack/tech-stack-background.png
Labels: Готово (есть 2 апрува)

#60 Feature/FAQ-component
  src/components/Faq/index.tsx
  src/components/Faq/styles.module.scss
  src/components/FaqCard/index.tsx
  src/components/FaqCard/interface.ts
  src/components/FaqCard/styles.module.scss
  src/components/MainPage/index.tsx
  src/constants/Faq/index.ts
  src/constants/Faq/type.ts
  src/images/icons/Plus.tsx
Labels: Готово (есть 2 апрува)

#79 feat: добавил компонент заднего фона для модальных окон
  src/components/Modal/index.tsx
  src/components/Modal/style.module.scss
  src/components/ModalBackground/index.tsx
  src/components/ModalBackground/style.module.scss
  src/components/Popup/index.tsx
  src/components/ProjectDescriptionModal/index.tsx
  src/components/ProjectDescriptionModal/style.module.scss
  src/components/StageCreate/style.module.scss
Labels: Готово (есть 2 апрува)

#100 Feature/reviews
  package-lock.json
  package.json
  public/images/icons/ArrowChevronIcon.tsx
  src/app/globals.scss
  src/components/MainPage/index.tsx
  src/components/Popup/style.module.scss
  src/components/Recommendations/RecommendationPreview/index.tsx
  src/components/Recommendations/RecommendationPreview/interface.ts
  src/components/Recommendations/RecommendationPreview/style.module.scss
  src/components/Recommendations/index.tsx
  src/components/Recommendations/style.module.scss
  src/components/notFound/index.tsx
  src/components/notFound/styles.module.scss
  src/constants/Recommendations/index.ts
  src/constants/index.ts
  src/images/recommendations/arrows.svg
  src/images/recommendations/background.png
  src/images/recommendations/center-slide.png
  src/images/recommendations/circle.svg
  src/images/recommendations/left-slide.png
  src/images/recommendations/right-slide.png
Labels: Новый PR

#105 feat(add-link-and-delete-images): добавила ссылки в футер и удалила п…
  public/images/recommendations/arrows.svg
  public/images/recommendations/background.png
  public/images/recommendations/center-slide.png
  public/images/recommendations/circle.svg
  public/images/recommendations/left-slide.png
  public/images/recommendations/right-slide.png
  src/components/Footer/index.tsx
  src/components/Footer/styles.module.scss
  src/components/Recommendations/index.tsx
  src/components/Recommendations/style.module.scss
  src/constants/Recommendations/index.ts
  src/images/recommendations/background.png
  src/images/recommendations/center-slide.png
  src/images/recommendations/left-slide.png
  src/images/recommendations/right-slide.png
Labels: Срочно проверить, Новый PR

#104 Fix/deleting-unused-header-folder
  src/components/Header/index.tsx
Labels: Один апрув

#103 Fix/contacts-pp
  src/components/Contacts/ContactsForm/Input/index.tsx
  src/components/Contacts/ContactsForm/Input/interface.ts
  src/components/Contacts/ContactsForm/Input/style.module.scss
  src/components/Contacts/ContactsForm/style.module.scss
  src/components/Contacts/index.tsx
  src/components/Contacts/style.module.scss
  src/components/Promo/PromoForm/style.module.scss
  src/constants/Contacts/index.ts
  src/constants/Promo/index.ts
Labels: Один апрув

#109 Feature/adding font
  src/app/globals.scss
  src/app/layout.tsx
  src/fonts/Involve-Medium.woff
  src/fonts/Involve-Medium.woff2
Labels: Готово (есть 2 апрува)

#101 Feature/footer-adaptive
  src/components/Footer/index.tsx
  src/components/Footer/styles.module.scss
Labels: Готово (есть 2 апрува)

#110 Refactor/change font
  src/app/globals.scss
  src/app/privacy-policy/style.module.scss
  src/components/AboutUs/style.module.scss
  src/components/Contacts/ContactsForm/Input/style.module.scss
  src/components/Contacts/ContactsForm/style.module.scss
  src/components/Contacts/style.module.scss
  src/components/Portfolio/Card/style.module.scss
  src/components/Promo/PromoForm/style.module.scss
  src/components/StageCreate/style.module.scss
  src/components/TechStack/CardLine/Card/style.module.scss
  src/components/TechStack/style.module.scss
  src/fonts/Cygre-Bold.ttf
  src/fonts/Cygre-Bold.woff
  src/fonts/Cygre-Bold.woff2
  src/fonts/Cygre.ttf
  src/fonts/Cygre.woff
  src/fonts/Cygre.woff2
Labels: Готово (есть 2 апрува)

#113 Feature/privacy-adaptive
  src/app/globals.scss
  src/app/privacy-policy/page.tsx
  src/app/privacy-policy/style.module.scss
Labels: Готово (есть 2 апрува)

#115 Feature/404-adaptive
  src/components/StageCreate/style.module.scss
  src/components/notFound/index.tsx
  src/components/notFound/styles.module.scss
Labels: Готово (есть 2 апрува)

#117 Feature/contacts-adaptive
  src/components/Contacts/ContactsForm/Input/ClearInputButton/styles.module.scss
  src/components/Contacts/ContactsForm/Input/styles.module.scss
  src/components/Contacts/ContactsForm/styles.module.scss
  src/components/Contacts/index.tsx
  src/components/Contacts/styles.module.scss
  src/components/Footer/styles.module.scss
Labels: Готово (есть 2 апрува), Исправлено (проверьте), Апрув + Мелкие правки

#119 Feature/site-description-modal-adaptive
  src/app/globals.scss
  src/components/MainPage/index.tsx
  src/components/ModalBackground/style.module.scss
  src/components/ProjectDescriptionModal/index.tsx
  src/components/ProjectDescriptionModal/style.module.scss
Labels: Готово (есть 2 апрува)

#123 Feature/interaction-adaptive
  public/images/interaction/attention-1280px.png
  public/images/interaction/communication-1280px.png
  public/images/interaction/design-1280px.png
  public/images/interaction/support-1280px.png
  src/components/Interaction/Step/index.tsx
  src/components/Interaction/Step/style.module.scss
  src/components/Interaction/index.tsx
  src/components/Interaction/styles.module.scss
  src/constants/Interaction/index.ts
  src/constants/Interaction/type.ts
Labels: Готово (есть 2 апрува)

#126 Feature/guarantees-adaptive
  public/images/guarantee/background-mobile.png
  public/images/guarantee/background-tablet.png
  src/app/globals.scss
  src/components/Guarantee/GuaranteeCard/index.tsx
  src/components/Guarantee/GuaranteeCard/styles.module.scss
  src/components/Guarantee/styles.module.scss
Labels: Готово (есть 2 апрува)

#131 Feature/tech-stack-adaptive
  src/components/TechStack/CardLine/Card/index.tsx
  src/components/TechStack/CardLine/Card/styles.module.scss
  src/components/TechStack/CardLine/index.tsx
  src/components/TechStack/CardLine/styles.module.scss
  src/components/TechStack/index.tsx
  src/components/TechStack/styles.module.scss
  src/constants/TechStack/index.tsx
Labels: Готово (есть 2 апрува)

#133 Feature/recommendations-adaptiv
  README.md
  src/components/Footer/styles.module.scss
  src/components/Recommendations/RecommendationPreview/index.tsx
  src/components/Recommendations/RecommendationPreview/style.module.scss
  src/components/Recommendations/index.tsx
  src/components/Recommendations/style.module.scss
Labels: Готово (есть 2 апрува)

#136 Feature: privacy-home-btn
  public/images/icons/ArrowBack.tsx
  src/app/privacy-policy/page.tsx
  src/app/privacy-policy/style.module.scss
Labels: Готово (есть 2 апрува)
