Repository Team-Code-Wizards/frontend, pull requests merged in 2024-03, with the labels that each got.

#239 Fix/about-us-top-padding
  src/components/AboutUs/styles.module.scss
Labels: Готово (можно заливать)

#243 Fix/other browsers
  src/components/Contacts/ContactsForm/index.tsx
  src/components/Contacts/ContactsForm/styles.module.scss
  src/components/Footer/styles.module.scss
  src/components/Navbar/style.module.scss
  src/components/Promo/PromoForm/index.tsx
Labels: Новый PR

#257 Feature/services-mobile-animation
  src/components/AdvertisingPromo/styles.module.scss
  src/components/Services/ServiceCard/style.module.scss
Labels: Готово (можно заливать)

#269 Feature: interaction-step-two-animation
  public/images/interaction/stepTwo/client.webp
  public/images/interaction/stepTwo/phone.webp
  public/images/interaction/stepTwo/team.webp
  src/components/Interaction/Step/Images/StepTwo/index.tsx
  src/components/Interaction/Step/Images/StepTwo/style.module.scss
  src/constants/Interaction/index.tsx
Labels: Новый PR

#275 Feature/animation-interaction
  public/images/interaction/attention-1280px.webp
  public/images/interaction/attention.webp
  public/images/interaction/communication-1280px.webp
  public/images/interaction/communication-390px.webp
  public/images/interaction/communication.webp
  src/components/Interaction/Step/Images/StepFive/style.module.scss
  src/components/Interaction/Step/Images/StepFour/index.tsx
  src/components/Interaction/Step/Images/StepFour/style.module.scss
Labels: Новый PR

#240 Feature/top-button
  public/images/icons/UpButton.tsx
  src/app/layout.tsx
  src/components/AboutUs/index.tsx
  src/components/UpButton/index.tsx
  src/components/UpButton/style.module.scss
Labels: Новый PR

#268 Feature/animation-modal
  src/app/globals.scss
  src/app/layout.tsx
  src/components/InfoMsgContext.tsx
  src/components/ModalBackground/index.tsx
  src/components/ModalBackground/style.module.scss
  src/components/Popup/index.tsx
  src/components/Popup/style.module.scss
  src/components/ProjectDescriptionModal/index.tsx
  src/components/ProjectDescriptionModal/style.module.scss
  src/components/WebsiteCreationModal/index.tsx
  src/components/WebsiteCreationModal/style.module.scss
  src/components/Сhoice/ChoiceCard/index.tsx
  src/components/Сhoice/ChoiceCard/style.module.scss
  src/components/Сhoice/index.tsx
  src/components/Сhoice/style.module.scss
Labels: Новый PR

#261 Feature/horizontal-modal
  src/components/Interaction/Step/Images/StepFour/index.tsx
  src/components/WebsiteCreationModal/ModalItem/index.tsx
  src/components/WebsiteCreationModal/ModalItem/style.module.scss
  src/components/WebsiteCreationModal/style.module.scss
Labels: Нужно доработать

#285 Fix/320px-center-blocks
  src/components/AboutUs/styles.module.scss
  src/components/Portfolio/Card/styles.module.scss
  src/components/Portfolio/styles.module.scss
  src/components/StageCreate/style.module.scss
Labels: Новый PR

#287 Fix/interaction-step-one
  src/components/AboutUs/index.tsx
  src/components/Interaction/Step/Images/StepOne/index.tsx
  src/components/Interaction/Step/Images/StepOne/style.module.scss
Labels: Исправлено (проверьте)

#313 Feat/capture
  .env.local
  package-lock.json
  package.json
  src/app/GoogleCaptchaWrapper.tsx
  src/app/api/recaptcha/route.ts
  src/app/globals.scss
  src/app/layout.tsx
  src/components/AdvertisingPromo/PromoForm/index.tsx
  src/components/Contacts/ContactsForm/index.tsx
  src/components/Footer/index.tsx
  src/components/WebsiteCreationModal/index.tsx
  src/service/captchaHandler.ts
Labels: Новый PR

#311 Feature/up-button-privacy-policy
  public/images/icons/ArrowBack.tsx
  src/app/privacy-policy/page.tsx
  src/components/AboutUs/index.tsx
Labels: Новый PR

#302 Fix: phone-validation
  src/constants/Contacts/contactsSchema.ts
  src/constants/Promo/promoSchema.ts
  src/constants/WebsiteCreationModal/siteOrderSchema.ts
Labels: Новый PR

#225 Fix/safari
  src/components/Contacts/ContactsForm/styles.module.scss
  src/components/MainPage/style.module.scss
  src/components/Promo/PromoForm/styles.module.scss
  src/components/WebsiteCreationModal/ModalItem/style.module.scss
Labels: На паузе
