Repository Team-Code-Wizards/frontend, pull requests merged in 2024-02, with the labels that each got.

#134 Feature/popup-adaptive
  public/images/popup/small-popup-background.webp
  src/app/globals.scss
  src/components/MainPage/index.tsx
  src/components/Popup/index.tsx
  src/components/Popup/style.module.scss
Labels: Готово (есть 2 апрува)

#140 Fix/change-keys
  package-lock.json
  package.json
  public/images/choice/IconStar.tsx
  src/components/Contacts/ContactsForm/Input/interface.ts
  src/components/Contacts/ContactsForm/index.tsx
  src/components/Faq/index.tsx
  src/components/Guarantee/index.tsx
  src/components/Interaction/index.tsx
  src/components/Modal/index.tsx
  src/components/Portfolio/Card/interface.ts
  src/components/Portfolio/index.tsx
  src/components/Promo/PromoForm/index.tsx
  src/components/Recommendations/RecommendationPreview/interface.ts
  src/components/Recommendations/index.tsx
  src/components/Services/index.tsx
  src/components/Сhoice/index.tsx
  src/constants/Choice/index.ts
  src/constants/Choice/type.ts
  src/constants/Contacts/index.ts
  src/constants/Faq/index.ts
  src/constants/Faq/type.ts
  src/constants/Guarantee/index.ts
  src/constants/Guarantee/type.ts
  src/constants/Interaction/index.ts
  src/constants/Interaction/type.ts
  src/constants/ModalWindow/index.ts
  src/constants/ModalWindow/type.ts
  src/constants/Portfolio/index.ts
  src/constants/Recommendations/index.ts
  src/constants/Services/index.ts
  src/constants/TechStack/index.tsx
Labels: Готово (есть 2 апрува)

#139 Feature/stage-create-adaptive
  public/images/stageCreate/clock-icon.webp
  public/images/stageCreate/stages-bg-390.webp
  public/images/stageCreate/stages-create-bg-1440.webp
  src/components/MainPage/index.tsx
  src/components/StageCreate/index.tsx
  src/components/StageCreate/style.module.scss
Labels: Готово (есть 2 апрува)

#141 Feature/services-adaptive-fix
  package-lock.json
  package.json
  public/images/icons/ArrowDownIcon.tsx
  src/app/globals.scss
  src/components/MainPage/index.tsx
  src/components/Portfolio/index.tsx
  src/components/Recommendations/index.tsx
  src/components/Services/index.tsx
  src/components/Services/style.module.scss
  src/constants/Services/index.ts
Labels: Готово (есть 2 апрува)

#146 Feature/website-creation-modal-adaptive
  package-lock.json
  src/components/MainPage/index.tsx
  src/components/Modal/ModalItem/index.tsx
  src/components/Modal/ModalItem/interface.ts
  src/components/Modal/ModalItem/style.module.scss
  src/components/Modal/style.module.scss
  src/components/WebsiteCreationModal/ModalItem/index.tsx
  src/components/WebsiteCreationModal/ModalItem/interface.ts
  src/components/WebsiteCreationModal/ModalItem/style.module.scss
  src/components/WebsiteCreationModal/index.tsx
  src/components/WebsiteCreationModal/style.module.scss
  src/constants/WebsiteCreationModal/index.ts
  src/constants/WebsiteCreationModal/type.ts
  src/constants/index.ts
Labels: Готово (есть 2 апрува)

#145 Feature/guarantees-adaptive
  public/images/guarantee/background.webp
  src/components/Guarantee/GuaranteeCard/index.tsx
  src/components/Guarantee/GuaranteeCard/styles.module.scss
  src/components/Guarantee/index.tsx
  src/components/Guarantee/styles.module.scss
  src/components/MainPage/index.tsx
  src/components/Portfolio/styles.module.scss
Labels: Готово (есть 2 апрува)

#149 Feature/recommendations-slider
  public/images/recommendations/middle-slide.webp
  src/components/Recommendations/RecommendationPreview/index.tsx
  src/components/Recommendations/RecommendationPreview/interface.ts
  src/components/Recommendations/RecommendationPreview/style.module.scss
  src/components/Recommendations/index.tsx
  src/components/Recommendations/style.module.scss
  src/constants/Recommendations/index.ts
Labels: Готово (есть 2 апрува)

#162 Feature/stages-logic
  public/images/stageCreate/content-icon.webp
  public/images/stageCreate/deployment-icon.webp
  public/images/stageCreate/development-icon.webp
  public/images/stageCreate/figma-icon.webp
  public/images/stageCreate/hosting-icon.webp
  public/images/stageCreate/html-icon.webp
  public/images/stageCreate/index.tsx
  public/images/stageCreate/optimization-icon.webp
  public/images/stageCreate/support-icon.webp
  public/images/stageCreate/testing-icon.webp
  src/components/Faq/FaqCard/index.tsx
  src/components/Faq/FaqCard/interface.ts
  src/components/Faq/FaqCard/styles.module.scss
  src/components/Faq/index.tsx
  src/components/StageCreate/index.tsx
  src/components/StageCreate/style.module.scss
  src/constants/StageCreate/index.ts
  src/constants/StageCreate/type.ts
Labels: Готово (есть 2 апрува)

#161 Feature/popup-modal-logic
  public/images/header/CloseIcon.tsx
  public/images/header/MenuIcon.tsx
  public/images/header/TelIcon.tsx
  public/images/icons/ArrowDownIcon.tsx
  public/images/modal/projectDescription/blog.webp
  public/images/modal/projectDescription/corp-site.webp
  public/images/modal/projectDescription/firm-site.webp
  public/images/modal/projectDescription/internet-shop.webp
  public/images/modal/projectDescription/landing.webp
  public/images/modal/projectDescription/site-by-tt.webp
  src/app/page.tsx
  src/app/privacy-policy/style.module.scss
  src/components/InfoMsgContext.tsx
  src/components/MainPage/index.tsx
  src/components/ModalBackground/index.tsx
  src/components/Navbar/index.tsx
  src/components/Navbar/style.module.scss
  src/components/Popup/index.tsx
  src/components/ProjectDescriptionModal/index.tsx
  src/components/ProjectDescriptionModal/style.module.scss
  src/components/Services/ServiceCard/index.tsx
  src/components/Services/ServiceCard/interface.ts
  src/components/Services/ServiceCard/style.module.scss
  src/components/Services/index.tsx
  src/components/Services/style.module.scss
  src/components/WebsiteCreationModal/index.tsx
  src/components/WebsiteCreationModal/style.module.scss
  src/constants/Navbar/index.ts
  src/constants/Services/index.ts
Labels: Апрув + Мелкие правки

#168 Feature/site-order-modal
  package-lock.json
  package.json
  src/components/Services/index.tsx
  src/components/WebsiteCreationModal/ModalItem/index.tsx
  src/components/WebsiteCreationModal/ModalItem/interface.ts
  src/components/WebsiteCreationModal/ModalItem/style.module.scss
  src/components/WebsiteCreationModal/index.tsx
  src/components/WebsiteCreationModal/style.module.scss
  src/constants/WebsiteCreationModal/index.ts
  src/constants/WebsiteCreationModal/prevData-not-used.ts
  src/constants/WebsiteCreationModal/siteOrderSchema.ts
  src/constants/WebsiteCreationModal/type.ts
  src/constants/index.ts
Labels: Готово (есть 2 апрува)

#170 Fix/stages-adaptive--faq-plus
  public/images/icons/Plus.tsx
  src/components/Faq/FaqCard/index.tsx
  src/components/Faq/FaqCard/styles.module.scss
  src/components/Services/style.module.scss
  src/components/Services/types.ts
  src/components/StageCreate/style.module.scss
  src/constants/StageCreate/index.ts
Labels: Готово (есть 2 апрува)

#175 Feature/price-change
  src/components/Services/ServiceCard/index.tsx
  src/components/Services/ServiceCard/interface.ts
  src/components/Services/ServiceCard/style.module.scss
  src/components/Services/ServiceCard/types.ts
  src/constants/Services/index.ts
Labels: Готово (есть 2 апрува)

#174 Feature/interaction-slider
  package-lock.json
  package.json
  public/images/interaction/approach-390px.webp
  public/images/interaction/communication-390px.webp
  public/images/interaction/design-390px.webp
  public/images/interaction/support-390px.webp
  public/images/interaction/testing-390px.webp
  src/app/api/send-mail/route.ts
  src/components/Interaction/Step/index.tsx
  src/components/Interaction/Step/style.module.scss
  src/components/Interaction/index.tsx
  src/components/Interaction/interface.ts
  src/components/Interaction/styles.module.scss
  src/components/Promo/PromoForm/index.tsx
  src/components/Recommendations/index.tsx
  src/components/Recommendations/style.module.scss
  src/constants/Interaction/index.ts
  src/constants/Interaction/type.ts
  src/service/mailservice.ts
  src/service/sendrequest.ts
  src/service/type.ts
Labels: Готово (есть 2 апрува)

#176 Feature/nodemailer
  .env.local
  .gitignore
  package-lock.json
  public/images/contacts/attachment.svg
  public/images/icons/ClearInputIcon.tsx
  public/images/icons/DeleteIcon.tsx
  public/images/icons/Plus.tsx
  src/components/Contacts/ContactsForm/Input/styles.module.scss
  src/components/Contacts/ContactsForm/index.tsx
  src/components/Contacts/ContactsForm/interface.ts
  src/components/Contacts/ContactsForm/styles.module.scss
  src/components/Contacts/index.tsx
  src/components/Input/ClearInputButton/index.tsx
  src/components/Input/ClearInputButton/styles.module.scss
  src/components/Input/index.tsx
  src/components/Input/interface.ts
  src/components/Input/styles.module.scss
  src/components/ModalBackground/index.tsx
  src/components/Popup/index.tsx
  src/components/Popup/style.module.scss
  src/components/Promo/PromoForm/index.tsx
  src/components/WebsiteCreationModal/ModalItem/index.tsx
  src/components/WebsiteCreationModal/index.tsx
  src/constants/Contacts/contactsSchema.ts
  src/constants/Contacts/index.ts
  src/constants/Contacts/type.ts
  src/constants/Promo/index.ts
  src/service/mailservice.ts
  src/service/sendrequest.ts
  src/service/submitter.ts
  src/service/type.ts
Labels: Готово (есть 2 апрува)

#177 Feature/site-order-modal-fix
  src/components/Guarantee/styles.module.scss
  src/components/Interaction/styles.module.scss
  src/components/ModalBackground/style.module.scss
  src/components/TechStack/styles.module.scss
  src/components/WebsiteCreationModal/ModalItem/index.tsx
  src/components/WebsiteCreationModal/ModalItem/style.module.scss
  src/components/WebsiteCreationModal/style.module.scss
Labels: Готово (есть 2 апрува)

#181 Feature/promo-form-control
  .gitignore
  src/app/globals.scss
  src/components/Contacts/ContactsForm/styles.module.scss
  src/components/Input/ClearInputButton/index.tsx
  src/components/Input/ClearInputButton/styles.module.scss
  src/components/Input/index.tsx
  src/components/Input/interface.ts
  src/components/Input/styles.module.scss
  src/components/ModalBackground/style.module.scss
  src/components/Promo/PromoForm/index.tsx
  src/components/Promo/PromoForm/interface.ts
  src/components/Promo/PromoForm/styles.module.scss
  src/components/Promo/index.tsx
  src/components/Services/index.tsx
  src/constants/Contacts/contactsSchema.ts
  src/constants/Contacts/index.ts
  src/constants/Contacts/type.ts
  src/constants/Promo/index.ts
  src/constants/Promo/promoSchema.ts
  src/constants/WebsiteCreationModal/siteOrderSchema.ts
  src/constants/index.ts
Labels: Готово (есть 2 апрува)

#182 Feature/price-change
  src/components/Services/ServiceCard/index.tsx
  src/components/Services/ServiceCard/types.ts
  src/components/Services/index.tsx
  src/components/Services/types.ts
Labels: Новый PR

#186 Fix/fix-navbar
  public/images/header/nav-bg.png
  public/images/header/nav-bg.webp
  src/components/Contacts/index.tsx
  src/components/Footer/index.tsx
  src/components/Navbar/index.tsx
  src/components/Navbar/style.module.scss
  src/components/Portfolio/Card/index.tsx
  src/components/Portfolio/index.tsx
  src/components/Promo/PromoForm/index.tsx
  src/components/Promo/index.tsx
  src/components/Recommendations/index.tsx
  src/components/Services/ServiceCard/index.tsx
Labels: Один апрув

#187 Fix/recommendations-slider
  package-lock.json
  package.json
  public/images/interaction/approach.webp
  public/images/interaction/attention.webp
  public/images/interaction/communication.webp
  public/images/interaction/design.webp
  public/images/interaction/support.webp
  public/images/interaction/testing.webp
  public/images/recommendations/middle-slide.webp
  src/components/Contacts/ContactsForm/index.tsx
  src/components/Guarantee/index.tsx
  src/components/Interaction/Step/index.tsx
  src/components/Interaction/Step/style.module.scss
  src/components/Interaction/index.tsx
  src/components/Interaction/styles.module.scss
  src/components/Portfolio/index.tsx
  src/components/Recommendations/index.tsx
  src/components/Recommendations/style.module.scss
  src/components/TechStack/index.tsx
  src/constants/Choice/index.ts
  src/constants/Guarantee/index.ts
  src/constants/Interaction/index.ts
  src/constants/Recommendations/index.ts
  src/service/mailservice.ts
  src/service/type.ts
Labels: Новый PR, Один апрув

#205 Feature/guarantee-hover
  src/components/Guarantee/GuaranteeCard/styles.module.scss
  src/components/Guarantee/interface.ts
Labels: Новый PR

#223 Fix/validation
  src/constants/Contacts/contactsSchema.ts
  src/constants/Promo/promoSchema.ts
Labels: Один апрув
